#include "tkph2.h"
tkph2 cms2;
namespace tas {
	vector<float> &trk_px() { return cms2.trk_px(); }
	vector<float> &trk_py() { return cms2.trk_py(); }
	vector<float> &trk_pz() { return cms2.trk_pz(); }
	vector<float> &trk_pt() { return cms2.trk_pt(); }
	vector<float> &trk_eta() { return cms2.trk_eta(); }
	vector<float> &trk_phi() { return cms2.trk_phi(); }
	vector<float> &trk_dxy() { return cms2.trk_dxy(); }
	vector<float> &trk_dz() { return cms2.trk_dz(); }
	vector<float> &trk_ptErr() { return cms2.trk_ptErr(); }
	vector<float> &trk_etaErr() { return cms2.trk_etaErr(); }
	vector<float> &trk_phiErr() { return cms2.trk_phiErr(); }
	vector<float> &trk_dxyErr() { return cms2.trk_dxyErr(); }
	vector<float> &trk_dzErr() { return cms2.trk_dzErr(); }
	vector<float> &trk_nChi2() { return cms2.trk_nChi2(); }
	vector<float> &trk_shareFrac() { return cms2.trk_shareFrac(); }
	vector<int> &trk_q() { return cms2.trk_q(); }
	vector<int> &trk_nValid() { return cms2.trk_nValid(); }
	vector<int> &trk_nInvalid() { return cms2.trk_nInvalid(); }
	vector<int> &trk_nPixel() { return cms2.trk_nPixel(); }
	vector<int> &trk_nStrip() { return cms2.trk_nStrip(); }
	vector<int> &trk_n3DLay() { return cms2.trk_n3DLay(); }
	vector<int> &trk_algo() { return cms2.trk_algo(); }
	vector<int> &trk_isHP() { return cms2.trk_isHP(); }
	vector<int> &trk_seedIdx() { return cms2.trk_seedIdx(); }
	vector<int> &trk_simIdx() { return cms2.trk_simIdx(); }
	vector<vector<int> > &trk_pixelIdx() { return cms2.trk_pixelIdx(); }
	vector<vector<int> > &trk_stripIdx() { return cms2.trk_stripIdx(); }
	vector<float> &sim_px() { return cms2.sim_px(); }
	vector<float> &sim_py() { return cms2.sim_py(); }
	vector<float> &sim_pz() { return cms2.sim_pz(); }
	vector<float> &sim_pt() { return cms2.sim_pt(); }
	vector<float> &sim_eta() { return cms2.sim_eta(); }
	vector<float> &sim_phi() { return cms2.sim_phi(); }
	vector<float> &sim_dxy() { return cms2.sim_dxy(); }
	vector<float> &sim_dz() { return cms2.sim_dz(); }
	vector<float> &sim_prodx() { return cms2.sim_prodx(); }
	vector<float> &sim_prody() { return cms2.sim_prody(); }
	vector<float> &sim_prodz() { return cms2.sim_prodz(); }
	vector<float> &sim_shareFrac() { return cms2.sim_shareFrac(); }
	vector<int> &sim_q() { return cms2.sim_q(); }
	vector<int> &sim_nValid() { return cms2.sim_nValid(); }
	vector<int> &sim_nPixel() { return cms2.sim_nPixel(); }
	vector<int> &sim_nStrip() { return cms2.sim_nStrip(); }
	vector<int> &sim_n3DLay() { return cms2.sim_n3DLay(); }
	vector<int> &sim_trkIdx() { return cms2.sim_trkIdx(); }
	vector<vector<int> > &sim_pixelIdx() { return cms2.sim_pixelIdx(); }
	vector<vector<int> > &sim_stripIdx() { return cms2.sim_stripIdx(); }
	vector<int> &pix_isBarrel() { return cms2.pix_isBarrel(); }
	vector<int> &pix_lay() { return cms2.pix_lay(); }
	vector<int> &pix_detId() { return cms2.pix_detId(); }
	vector<int> &pix_nSimTrk() { return cms2.pix_nSimTrk(); }
	vector<int> &pix_simTrkIdx() { return cms2.pix_simTrkIdx(); }
	vector<int> &pix_particle() { return cms2.pix_particle(); }
	vector<int> &pix_process() { return cms2.pix_process(); }
	vector<int> &pix_bunchXing() { return cms2.pix_bunchXing(); }
	vector<int> &pix_event() { return cms2.pix_event(); }
	vector<float> &pix_x() { return cms2.pix_x(); }
	vector<float> &pix_y() { return cms2.pix_y(); }
	vector<float> &pix_z() { return cms2.pix_z(); }
	vector<float> &pix_xx() { return cms2.pix_xx(); }
	vector<float> &pix_xy() { return cms2.pix_xy(); }
	vector<float> &pix_yy() { return cms2.pix_yy(); }
	vector<float> &pix_yz() { return cms2.pix_yz(); }
	vector<float> &pix_zz() { return cms2.pix_zz(); }
	vector<float> &pix_zx() { return cms2.pix_zx(); }
	vector<float> &pix_xsim() { return cms2.pix_xsim(); }
	vector<float> &pix_ysim() { return cms2.pix_ysim(); }
	vector<float> &pix_zsim() { return cms2.pix_zsim(); }
	vector<float> &pix_pxsim() { return cms2.pix_pxsim(); }
	vector<float> &pix_pysim() { return cms2.pix_pysim(); }
	vector<float> &pix_pzsim() { return cms2.pix_pzsim(); }
	vector<float> &pix_pathprop() { return cms2.pix_pathprop(); }
	vector<float> &pix_xsimprop() { return cms2.pix_xsimprop(); }
	vector<float> &pix_ysimprop() { return cms2.pix_ysimprop(); }
	vector<float> &pix_zsimprop() { return cms2.pix_zsimprop(); }
	vector<float> &pix_pxsimprop() { return cms2.pix_pxsimprop(); }
	vector<float> &pix_pysimprop() { return cms2.pix_pysimprop(); }
	vector<float> &pix_pzsimprop() { return cms2.pix_pzsimprop(); }
	vector<float> &pix_eloss() { return cms2.pix_eloss(); }
	vector<float> &pix_radL() { return cms2.pix_radL(); }
	vector<float> &pix_bbxi() { return cms2.pix_bbxi(); }
	vector<int> &str_isBarrel() { return cms2.str_isBarrel(); }
	vector<int> &str_isStereo() { return cms2.str_isStereo(); }
	vector<int> &str_det() { return cms2.str_det(); }
	vector<int> &str_lay() { return cms2.str_lay(); }
	vector<int> &str_detId() { return cms2.str_detId(); }
	vector<int> &str_nSimTrk() { return cms2.str_nSimTrk(); }
	vector<int> &str_simTrkIdx() { return cms2.str_simTrkIdx(); }
	vector<int> &str_particle() { return cms2.str_particle(); }
	vector<int> &str_process() { return cms2.str_process(); }
	vector<int> &str_bunchXing() { return cms2.str_bunchXing(); }
	vector<int> &str_event() { return cms2.str_event(); }
	vector<float> &str_x() { return cms2.str_x(); }
	vector<float> &str_y() { return cms2.str_y(); }
	vector<float> &str_z() { return cms2.str_z(); }
	vector<float> &str_xx() { return cms2.str_xx(); }
	vector<float> &str_xy() { return cms2.str_xy(); }
	vector<float> &str_yy() { return cms2.str_yy(); }
	vector<float> &str_yz() { return cms2.str_yz(); }
	vector<float> &str_zz() { return cms2.str_zz(); }
	vector<float> &str_zx() { return cms2.str_zx(); }
	vector<float> &str_xsim() { return cms2.str_xsim(); }
	vector<float> &str_ysim() { return cms2.str_ysim(); }
	vector<float> &str_zsim() { return cms2.str_zsim(); }
	vector<float> &str_pxsim() { return cms2.str_pxsim(); }
	vector<float> &str_pysim() { return cms2.str_pysim(); }
	vector<float> &str_pzsim() { return cms2.str_pzsim(); }
	vector<float> &str_eloss() { return cms2.str_eloss(); }
	vector<float> &str_radL() { return cms2.str_radL(); }
	vector<float> &str_bbxi() { return cms2.str_bbxi(); }
	vector<int> &glu_isBarrel() { return cms2.glu_isBarrel(); }
	vector<int> &glu_det() { return cms2.glu_det(); }
	vector<int> &glu_lay() { return cms2.glu_lay(); }
	vector<int> &glu_detId() { return cms2.glu_detId(); }
	vector<int> &glu_monoIdx() { return cms2.glu_monoIdx(); }
	vector<int> &glu_stereoIdx() { return cms2.glu_stereoIdx(); }
	vector<float> &glu_x() { return cms2.glu_x(); }
	vector<float> &glu_y() { return cms2.glu_y(); }
	vector<float> &glu_z() { return cms2.glu_z(); }
	vector<float> &glu_xx() { return cms2.glu_xx(); }
	vector<float> &glu_xy() { return cms2.glu_xy(); }
	vector<float> &glu_yy() { return cms2.glu_yy(); }
	vector<float> &glu_yz() { return cms2.glu_yz(); }
	vector<float> &glu_zz() { return cms2.glu_zz(); }
	vector<float> &glu_zx() { return cms2.glu_zx(); }
	vector<float> &glu_radL() { return cms2.glu_radL(); }
	vector<float> &glu_bbxi() { return cms2.glu_bbxi(); }
	float &bsp_x() { return cms2.bsp_x(); }
	float &bsp_y() { return cms2.bsp_y(); }
	float &bsp_z() { return cms2.bsp_z(); }
	float &bsp_sigmax() { return cms2.bsp_sigmax(); }
	float &bsp_sigmay() { return cms2.bsp_sigmay(); }
	float &bsp_sigmaz() { return cms2.bsp_sigmaz(); }
	vector<float> &see_lh_px() { return cms2.see_lh_px(); }
	vector<float> &see_lh_py() { return cms2.see_lh_py(); }
	vector<float> &see_lh_pz() { return cms2.see_lh_pz(); }
	vector<float> &see_lh_pt() { return cms2.see_lh_pt(); }
	vector<float> &see_lh_eta() { return cms2.see_lh_eta(); }
	vector<float> &see_lh_phi() { return cms2.see_lh_phi(); }
	vector<float> &see_lh_x() { return cms2.see_lh_x(); }
	vector<float> &see_lh_y() { return cms2.see_lh_y(); }
	vector<float> &see_lh_z() { return cms2.see_lh_z(); }
	vector<float> &see_pca_px() { return cms2.see_pca_px(); }
	vector<float> &see_pca_py() { return cms2.see_pca_py(); }
	vector<float> &see_pca_pz() { return cms2.see_pca_pz(); }
	vector<float> &see_pca_pt() { return cms2.see_pca_pt(); }
	vector<float> &see_pca_eta() { return cms2.see_pca_eta(); }
	vector<float> &see_pca_phi() { return cms2.see_pca_phi(); }
	vector<float> &see_pca_x() { return cms2.see_pca_x(); }
	vector<float> &see_pca_y() { return cms2.see_pca_y(); }
	vector<float> &see_pca_z() { return cms2.see_pca_z(); }
	vector<float> &see_pca_dxy() { return cms2.see_pca_dxy(); }
	vector<float> &see_pca_dz() { return cms2.see_pca_dz(); }
	vector<float> &see_pca_ptErr() { return cms2.see_pca_ptErr(); }
	vector<float> &see_pca_etaErr() { return cms2.see_pca_etaErr(); }
	vector<float> &see_pca_phiErr() { return cms2.see_pca_phiErr(); }
	vector<float> &see_pca_dxyErr() { return cms2.see_pca_dxyErr(); }
	vector<float> &see_pca_dzErr() { return cms2.see_pca_dzErr(); }
	vector<float> &see_chi2() { return cms2.see_chi2(); }
	vector<int> &see_q() { return cms2.see_q(); }
	vector<int> &see_nValid() { return cms2.see_nValid(); }
	vector<int> &see_nPixel() { return cms2.see_nPixel(); }
	vector<int> &see_nGlued() { return cms2.see_nGlued(); }
	vector<int> &see_nStrip() { return cms2.see_nStrip(); }
	vector<int> &see_algo() { return cms2.see_algo(); }
	vector<vector<int> > &see_pixelIdx() { return cms2.see_pixelIdx(); }
	vector<vector<int> > &see_gluedIdx() { return cms2.see_gluedIdx(); }
	vector<vector<int> > &see_stripIdx() { return cms2.see_stripIdx(); }
	vector<int> &algo_offset() { return cms2.algo_offset(); }
}
